import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';

import "./globals.css";
import Header from "./components/HeaderFol/Header";
import Hero from "./components/Hero";
import NextBreadcrumb from "./components/Breadcrumb/Breadcrumb";
import BootstrapClient from "./components/BootstrapClient";
import { AOSInit } from "./lib/aos-anima";

import '@fortawesome/fontawesome-free/css/all.css';






const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <AOSInit />
      <body className={inter.className}>
        
       <Header />
       <Hero />
       <NextBreadcrumb 
       homeElement={'Home'}
       separator={<span className="mx-3"> | </span>}
       activeClasses='breacrumb-active-item'
       containerClasses='breadcrumb  ' 
       listClasses='breadcrumb-item'
       capitalizeLinks
       />
        {children}
        <BootstrapClient />
        </body>
    </html>
  );
}
